[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solrefer = "EwUYBCEJYXkVNK49wwoYhi2T7m83jBLzhXvEG71UQ3kM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
