name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo +nightly fmt --all -- --check

  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: actions/cache@v4
        name: Cache Dependencies
        id: cache-deps
        with:
          path: |
            ~/.cargo/bin/anchor
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            ~/.cache/solana
            ~/.local/share/solana/install
          key: deps-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      # Install dependencies only if cache miss
      - name: Install Solana
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor CLI
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install 0.28.0
          avm use 0.28.0

      # Run checks in parallel where possible
      - name: Run Clippy
        run: RUSTFLAGS="-A unexpected_cfgs" cargo clippy -- -D warnings

      - name: Run Build and Tests
        run: |
          RUSTFLAGS="-A unexpected_cfgs" anchor build
          RUSTFLAGS="-A unexpected_cfgs" anchor test
